package com.atom.mvc.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
		return (M)this;
	}

	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public M setModifytime(java.util.Date modifytime) {
		set("modifytime", modifytime);
		return (M)this;
	}

	public java.util.Date getModifytime() {
		return get("modifytime");
	}

	public M setCompanyId(java.lang.Integer companyId) {
		set("company_id", companyId);
		return (M)this;
	}

	public java.lang.Integer getCompanyId() {
		return get("company_id");
	}

	public M setLoginName(byte[] loginName) {
		set("login_name", loginName);
		return (M)this;
	}

	public byte[] getLoginName() {
		return get("login_name");
	}

	public M setPassword(byte[] password) {
		set("password", password);
		return (M)this;
	}

	public byte[] getPassword() {
		return get("password");
	}

	public M setUserName(byte[] userName) {
		set("user_name", userName);
		return (M)this;
	}

	public byte[] getUserName() {
		return get("user_name");
	}

	public M setPhone(byte[] phone) {
		set("phone", phone);
		return (M)this;
	}

	public byte[] getPhone() {
		return get("phone");
	}

	public M setLastLogin(java.util.Date lastLogin) {
		set("last_login", lastLogin);
		return (M)this;
	}

	public java.util.Date getLastLogin() {
		return get("last_login");
	}

	public M setLoginIp(java.lang.String loginIp) {
		set("login_ip", loginIp);
		return (M)this;
	}

	public java.lang.String getLoginIp() {
		return get("login_ip");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public M setErrorCount(java.lang.Integer errorCount) {
		set("error_count", errorCount);
		return (M)this;
	}

	public java.lang.Integer getErrorCount() {
		return get("error_count");
	}

	public M setIsAdmin(java.lang.Integer isAdmin) {
		set("is_admin", isAdmin);
		return (M)this;
	}

	public java.lang.Integer getIsAdmin() {
		return get("is_admin");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

}
