package com.atom.mvc.model;

import com.atom.mvc.model.base.BaseSyslog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Syslog extends BaseSyslog<Syslog> {
	public static final Syslog dao = new Syslog().dao();
}
