package com.atom.mvc.model;

import com.atom.mvc.model.base.BaseUserrole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Userrole extends BaseUserrole<Userrole> {
	public static final Userrole dao = new Userrole().dao();
}
